[tool.uv.sources]
kiui = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
audiocraft = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
konfuzio-sdk = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
kornia = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
audiolm-pytorch = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
kornia-moons = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
kraken = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
auralis = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
kwarray = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
auraloss = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
kwimage = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
auto-gptq = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
labml-nn = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
lagent = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
laion-clap = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
autoawq = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
lale = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
autoawq-kernels = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
lama-cleaner = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
"autogluon.multimodal" = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
lancedb = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
"autogluon.tabular" = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
langcheck = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
langkit = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
== 'Linux'" }]
